name: Build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/.tmp'
      - '**/.gitignore'
      - '**/.gitattributes'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip Setup Wizard to package the Blender Addon
        run: zip -r release.zip ./setup_wizard -x
