name: Build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/.tmp'
      - '**/.gitignore'
      - '**/.gitattributes'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Setup Wizard Package
        uses: actions/upload-artifact@v3
        with:
          name: Setup_Wizard_UI_Addon
          path: setup_wizard/
