name: Package and Release Addons

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - '**/.tmp'
      - '**/.gitignore'
      - '**/.gitattributes'
  workflow_dispatch:

permissions:
  actions: write
  checks: read
  contents: write
  packages: write
  deployments: write
  id-token: write
  issues: read
  discussions: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  build_standalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Standalone Addon Folder Structure
        run: |
          rm -r setup_wizard/tests
          mkdir -p dist/setup_wizard/setup_wizard
          mv setup_wizard dist/setup_wizard
      - name: Upload Standalone Setup Wizard Package
        uses: actions/upload-artifact@v4
        with:
          name: "Character_Setup_Wizard_Addon_${{github.ref_name}}_Standalone"
          path: dist/setup_wizard/
  build_regular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Addon Folder Structure
        run: |
          rm -r setup_wizard/tests
          rm -r setup_wizard/dependencies
          mkdir -p dist/setup_wizard/setup_wizard
          mv setup_wizard dist/setup_wizard
      - name: Upload Setup Wizard Package
        uses: actions/upload-artifact@v4
        with:
          name: "Character_Setup_Wizard_Addon_${{github.ref_name}}"
          path: dist/setup_wizard/
  tagged-release:
    name: Tagged Release
    needs: [build_standalone, build_regular]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Character_Setup_Wizard_Addon_${{github.ref_name}}_Standalone
      - uses: actions/download-artifact@v4
        name: Character_Setup_Wizard_Addon_${{github.ref_name}}
      - name: Display structure of downloaded files
        run: ls -R
      - name: Zip folders
        run: |
            cd Character_Setup_Wizard_Addon_${{github.ref_name}}_Standalone
            zip -r Character_Setup_Wizard_Addon_${{github.ref_name}}_Standalone.zip setup_wizard -x ".git*"
            cd ../Character_Setup_Wizard_Addon_${{github.ref_name}}
            zip -r Character_Setup_Wizard_Addon_${{github.ref_name}}.zip setup_wizard -x ".git*"
            ls -R
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          files: |
            Character_Setup_Wizard_Addon_${{github.ref_name}}_Standalone/Character_Setup_Wizard_Addon_${{github.ref_name}}_Standalone.zip
            Character_Setup_Wizard_Addon_${{github.ref_name}}/Character_Setup_Wizard_Addon_${{github.ref_name}}.zip
